//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonInstanceFactory.Sample.Client.GreetingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GreetingService.IGreetingService")]
    public interface IGreetingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/Greet", ReplyAction="http://tempuri.org/IGreetingService/GreetResponse")]
        string Greet(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreetingServiceChannel : CommonInstanceFactory.Sample.Client.GreetingService.IGreetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreetingServiceClient : System.ServiceModel.ClientBase<CommonInstanceFactory.Sample.Client.GreetingService.IGreetingService>, CommonInstanceFactory.Sample.Client.GreetingService.IGreetingService {
        
        public GreetingServiceClient() {
        }
        
        public GreetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Greet(string name) {
            return base.Channel.Greet(name);
        }
    }
}
